name: Deploy to WordPress.org
on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - with:
          node-version: ${{ matrix.node-version }}
      - run: composer install --no-dev --prefer-dist --no-progress --no-suggest
      - run: npm ci

      - name: WordPress plugin deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: mihdan-lite-youtube-embed