name: Deploy to WordPress.org
on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --no-progress --no-suggest

      - name: WordPress plugin deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: mihdan-lite-youtube-embed

      - name: Upload release asset
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: ${{ github.workspace }}/${{ github.event.repository.name }}.zip
            asset_name: ${{ github.event.repository.name }}.zip
            asset_content_type: application/zip