name: Deploy to WordPress.org
on:
  push:
    branches:
      - master
jobs:
  build:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - with:
          node-version: ${{ matrix.node-version }}
      - run: composer install --no-dev --prefer-dist --no-progress --no-suggest
      - run: npm ci
      - run: gulp default