name: Deploy to WordPress.org
on:
  push:
    branches:
      - master
jobs:
  build:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install composer requirements
        run: composer install --no-dev --prefer-dist --no-progress --no-suggest

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Init Node
        run: npm ci

      - name: Gulp
        run: gulp default